// Generated by CoffeeScript 1.6.3
(function() {
  import ui.View;
  import math.util;
  var Dot, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dot = (function(_super) {
    __extends(Dot, _super);

    function Dot() {
      _ref = Dot.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Dot.patterns = ['#3482ec', '#814000', '#e0d430', '#d74dbe', '#54ca5d'];

    Dot.random_pattern = function() {
      return math.util.random(0, Dot.patterns.length);
    };

    Dot.prototype.init = function(grid_i, grid_j, pattern_no, opts) {
      this.grid_i = grid_i;
      this.grid_j = grid_j;
      this.pattern_no = pattern_no;
      opts = merge(opts, {
        backgroundColor: Dot.patterns[this.pattern_no]
      });
      return Dot.__super__.init.call(this, opts);
    };

    return Dot;

  })(ui.View);

  exports = Dot;

}).call(this);
