// Generated by CoffeeScript 1.6.3
(function() {
  import ui.ImageView;
  import ui.resource.Image as Image;
  var RetinaImageView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RetinaImageView = (function(_super) {
    __extends(RetinaImageView, _super);

    function RetinaImageView() {
      _ref = RetinaImageView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    RetinaImageView.prototype.init = function(opts) {
      var imagePath, img,
        _this = this;
      imagePath = opts.image;
      opts.image = void 0;
      RetinaImageView.__super__.init.call(this, opts);
      if (GC.app.view.style.scale === 2) {
        img = new Image({
          url: imagePath.slice(0, -4) + '@2x' + imagePath.slice(-4, 1000)
        });
        img.doOnLoad(function(e) {
          var img2;
          if (e !== null && e.NoImage) {
            img2 = new Image({
              url: imagePath
            });
            return _this.setImage(img2);
          } else {
            return _this.setImage(img);
          }
        });
      } else {
        img = new Image({
          url: imagePath
        });
        this.setImage(img);
      }
      return true;
    };

    return RetinaImageView;

  })(ui.ImageView);

  exports = RetinaImageView;

}).call(this);
