// Generated by CoffeeScript 1.6.3
(function() {
  var Setting;

  Setting = (function() {
    function Setting() {}

    Setting.game_width = 320;

    Setting.game_height = 480;

    return Setting;

  })();

  exports = Setting;

}).call(this);
